// Warning: This file is automatically synced from https://github.com/ipfs/ci-sync so if you want to change it, please change it there and ask someone to sync all repositories.
javascript([
  'node_modules': [
    'libp2p': 'github:libp2p/js-libp2p#feat/priv-net',
    'libp2p-switch': 'github:libp2p/js-libp2p-switch#feat/priv-net',
    'ipfsd-ctl': 'github:ipfs/js-ipfsd-ctl#master',
    'libp2p-pnet': 'github:libp2p/js-libp2p-pnet#feat/initial',
    'ipfs-repo': 'github:ipfs/js-ipfs-repo#feat/pnet'
  ]
])
